### ISSUE TITLE
unable bring up jenkins due to connection with fluentd failure

### ISSUE THREAD

**Issue by jacklin5168** [mdiazn80/grauss-docker-compose-bak#18]
[root@localhost grauss-docker-compose-bak-1.1.0]# docker-compose up -d
Removing jenkins
postgres-keycloak is up-to-date
prometheus-fed is up-to-date
alertmanager is up-to-date
blackbox is up-to-date
consul is up-to-date
elasticsearch is up-to-date
keycloak is up-to-date
prometheus is up-to-date
vault is up-to-date
logstash is up-to-date
Starting fluentd ... 
kibana is up-to-date
Starting fluentd ... done
Starting cdd27db0d78c_jenkins ... error

ERROR: for cdd27db0d78c_jenkins  Cannot start service jenkins: failed to initialize logging driver: dial tcp: i/o timeout

ERROR: for jenkins  Cannot start service jenkins: failed to initialize logging driver: dial tcp: i/o timeout
ERROR: Encountered errors while bringing up the project.

**Comment by mdiazn80** [comment]
This is an old version. I recommend [https://github.com/mdiazn80/grauss-docker-compose](grauss-docker-compose). Anyway I have fixed the error.
